### PR TITLE
Fixed DB test # Means to fix the failed jobs not being written in the db due the logs not being retrieved

### PR DESCRIPTION
**Pull request by kinow**
In GitLab by @dbeltrankyl on Dec 9, 2024, 19:10

This fixes: 

* !527 , in line with this merge, now a job can't be put in the UniqueQueue if it has no ID.

* Fixed an issue with failed jobs when chunks are> 3, retrials are> 5, and the job fulfills the 3 retrials. 

The fix consists of adding a copy(job) in the put method. 

I really thought that was what you put in the multiprocess.Queue() is always a copy of your actual instance. However, I saw that it was affecting the jobs in the Queue. 

Since I have to add a copy ( not a deep one, tho, so it shouldn't be expensive), an alternative would be to pass job.id, fail_count, out , err, status, and create a new job in the log_recovery process.

* Reorganized the log retrievals in case of failure 

Now, instead of reconnecting to the platform and not going through each job in the queue, AS will get all the jobs from the queue and then reconnect if any job has an issue. 

This avoids the issue of not getting the rest of the jobs that really have err and out files at the end of the main process

* Now the check of if the job is recovered or not, is only done at the end and at the start instead of in the middle.

Tomorrow, I'll add to the regression test, a check for the log retrieval names

* Removes unused stuff

* Pipeline should now always works, the nature of the issue was tied to the CPU clock I believe.

### CODE REVIEW

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 9, 2024, 19:10

requested review from @kinow

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 10:40

added 1 commit

<ul><li>109d9729 - Now the db test also checks the stat and job_names in the filesystem</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37078&start_sha=533ea03d30165629a445eea4820214ec8b891f2f)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 10:45

Added the remaining test, ready to review @kinow 

For testing this branch, I had this test.yml file:

```yaml
CONFIG:
  # Current version of autosubmit.
  AUTOSUBMIT_VERSION: "4.1.11"
  # Maximum number of jobs permitted in the waiting status.
  MAXWAITINGJOBS: 20 # <- This can affect as it alters the time to process everything
  # Total number of jobs in the workflow.
  TOTALJOBS: 20 # <- This can affect as it alter the time to process everything
  SAFETYSLEEPTIME: 0 # <- IMPORTANT to set it to 0 
MAIL:
  NOTIFICATIONS: False
  TO:
STORAGE:
  TYPE: pkl
  COPY_REMOTE_LOGS: true
PROJECT:
  # Type of the project.
  PROJECT_TYPE: none
  # Folder to hold the project sources.
  PROJECT_DESTINATION: git_project
GIT:
  PROJECT_ORIGIN: "blabla"
  PROJECT_BRANCH: "blabla"
  PROJECT_COMMIT: ''
  PROJECT_SUBMODULES: ''
  FETCH_SINGLE_BRANCH: true
```

```yaml
EXPERIMENT:
  DATELIST: 20221101
  MEMBERS: fc0
  CHUNKSIZEUNIT: month
  CHUNKSIZE: 2
  NUMCHUNKS: 3 # <- IMPORTANT, with 1 chunk doesn't happen, with 2 chunks sometimes
  CHUNKINI: ''
  CALENDAR: standard
JOBS:
    job:
        SCRIPT: |
            decho "Hello World" # Force failure we want to test the retrials
        RUNNING: chunk
        wallclock: 00:01
        PLATFORM: local # marenostrum5 requires other branches fixes
        Retrials: 15 # augment or reduce this.. in my laptop I had issues +15 
```

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 11:48

I Need to rebase it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 11:57

added 4 commits

<ul><li>109d9729...22e0518e - 2 commits from branch <code>4.1.12-dev-branch</code></li><li>189c3ddd - Fixed DB test</li><li>a50f230b - Now the db test also checks the stat and job_names in the filesystem</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37115&start_sha=109d9729e9574d112958a2c34f8cd2b0ace526f7)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 12:05

Rebased without issues

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 10, 2024, 14:08

mentioned in issue digital-twins/de_340-2/workflow#747

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/job/job_list.py line 2686](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..a50f230b15c2448823b23b1748806c65524bb385#diff-bad488e977334d250f2df049877c45f3R2686)



This is showing as not covered by the tests.

Also, the logic seems to be this now:

```py
if log_recovered:
  # do something
elif not job.updated_log and str(as_conf.platforms_data.get(job.platform.name, {}).get('DISABLE_RECOVERY_THREADS', "false")).lower() == "false":
  if new_run:
    # do something else

return ...
```

Wouldn't it be easier to move `new_run` to the `elif`?

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/job/job_list.py line 2727](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-bad488e977334d250f2df049877c45f3L2727)



Showing as not covered, could you confirm if the new code is being tested? Otherwise, I can run everything with the debugger and verify it too.

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/platforms/platform.py line 54](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R54)



Maybe move the comment to before the code? This adds new PEP8 warnings in the IDE due to line length and single space before comment.

Also,

> Without copy, the process seems to modify the job for other retrials.. My guess is that the object is not serialized until it is get from the queue.

I am not sure if I follow how this is fixing the issue.

From the Python docs, looks like `multiprocessing.queues.Queue` will start a thread with locks, it's backed by a `collections.deque`, and returns pickled objects (copies),

```bash
$ python3
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses import dataclass
>>> from multiprocessing import Queue
>>> queue = Queue()
>>> @dataclass
... class Obj:
...   name: str
... 
>>> obj = Obj(name='John')
>>> 
>>> queue.put(obj)
>>> 
>>> obj.name='Olivia'
>>> obj
Obj(name='Olivia')
>>> queue.get()
Obj(name='John')
>>> obj
Obj(name='Olivia')
```

Could you confirm that there was another process modifying a value, and causing the test failures? Or could it be that another change is fixing that? Or maybe I'm misunderstanding the bug and/or fix .

https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues

image

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/platforms/platform.py line 854](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R854)



Shouldn't a job always have an ID that's set to a valid value before reaching this part of the code? Couldn't it hide a bug somewhere else?

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/platforms/platform.py line 946](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R946)



I think this means we won't catch [a possible `OSError`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.empty), but I think we should still be capturing it elsewhere (`OSError` extends `Exception`).

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [test/unit/test_database_regression.py line 258](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-b8e691c53e499027349985b088df4261L258)



I think the test was doing

1) prepare expid and DB
2) SELECT * FROM job_data to retrieve all data
3) process and verify that the data is correct (submit, finish, start, etc)
4) then retrieve from job_data again, some counts grouped by job_name
5) verify that we have the expected number

But you changed it and now the expected number is the initial number of rows in job_data, it process and verify that the data is correct, and then checks that the log files exist.

Couldn't we leave step #4, checking the grouped data? Or did it change (why?)?

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/autosubmit.py line 2368](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..a50f230b15c2448823b23b1748806c65524bb385#diff-fb87ba4e4225b357016f4298108bcf0dR2368)



Delete? :point_up:

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Commented on [autosubmit/autosubmit.py line 2199](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-fb87ba4e4225b357016f4298108bcf0dR2199)



This looks like a good idea, to check logs when exiting. But wasn't this change to fix the database test? It looks like the database test was modified here to look for the number of log files, and this merge request is now also fixing/modifying the logic for logs.

Couldn't we have it in another merge request? I thought we had agreed to keep our merge requests as small as possible (I think there was a thread somewhere where @mcastril also commented about it...)

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 10, 2024, 16:43

Left some comments about test coverage, and to clarify what's the main goal of the merge request (a single fix or multiple fixes here?).

Depending on the coverage of tests I can do a few tests, or review the code more thoroughly (I only used the Gitlab UI today, and started doing it after 4PM, so my brain is probably already tired, sorry if some comments are not clear/helpful).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:07

Commented on [autosubmit/platforms/platform.py line 54](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R54)



> Could you confirm that there was another process modifying a value, and causing the test failures? 

I don't understand it 100% myself, but I explain what I observed.

Jobs configuration has:

* 3 jobs ( chunks)
* retrials: 5 
* The script is forced to fail

```yaml
JOBS:
    job:
        SCRIPT: |
            decho "Hello World with id=Failed"
        RUNNING: chunk
        wallclock: 00:01
        PLATFORM: local
        retrials: 5
```

What should we expect ( more or less as it has some delay gathering stuff), and it is fixed with the copy()

* Job first retrial completed
* [Process A] Job and with updated fail_count 0 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 0 is retrieved
* Job retrial completed
* [Process A] Job and with updated fail_count 1 -> put in the queue()
* [Process B] (get from queue) Job.name and retrial 1 is retrieved 
* Job retrial completed
* [Process A] Job and with updated fail_count 2 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 2 is retrieved
* Job retrial completed
* [Process A] Job and with updated fail_count 3 -> put in the queue()
* Job retrial completed 
* [Process A] Job and with updated fail_count 4 -> put in the queue()
* Job retrial completed 
* [Process A] Job and with updated fail_count 5 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 3 is retrieved
* [Process B] (get from queue) Job.name and retrial 4 is retrieved
* [Process B] (get from queue) Job.name and retrial 5 is retrieved

What was happening: 

* Job retrial completed
* [Process A] Job and with updated fail_count 0 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 0 is retrieved
* Job retrial completed
* [Process A] Job and with updated fail_count 1 -> put in the queue()
* [Process B] (get from queue) Job.name and retrial 1 is retrieved 
* Job retrial completed
* [Process A] Job and with updated fail_count 2 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 2 is retrieved
* Job retrial completed
* [Process A] Job and with updated fail_count 3 -> put in the queue()
* Job retrial completed 
* [Process A] Job and with updated fail_count 4 -> put in the queue()
* Job retrial completed 
* [Process A] Job and with updated fail_count 5 -> put in the queue() 
* [Process B] (get from queue) Job.name and retrial 5 is retrieved # should be 3
* [Process B] (get from queue) Job.name and retrial 5 does not exist  # should be 4
* [Process B] (get from queue) Job.name and retrial 5 does not exist # is 5, but the log is already retrieved

The queue should have (job,job,job), each one with (job._fail_count=3,job._fail_count=4,job._fail_count=5)

So, it seems that the fail_count update and, afterward, sending it to the queue affected the current other jobs. I don't understand how this happens, but the copy solves it.

You can test it manually.

> Or could it be that another change is fixing that? Or maybe I'm misunderstanding the bug and/or fix .

I'm 100% sure that the copy is what fixes it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:10

Commented on [autosubmit/job/job_list.py line 2727](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-bad488e977334d250f2df049877c45f3L2727)



Hello @kinow 

I mainly used the regression test so that's why is shows as not covered, 

The regression test is reaching it but I'll do a unit test

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:11

Commented on [autosubmit/job/job_list.py line 2686](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..a50f230b15c2448823b23b1748806c65524bb385#diff-bad488e977334d250f2df049877c45f3R2686)



Sure, I didn't think about it.

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 11, 2024, 10:12

Commented on [autosubmit/job/job_list.py line 2727](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-bad488e977334d250f2df049877c45f3L2727)



Hi @dbeltrankyl or if you think it wouldn't be too difficult, perhaps you could share the regression tests with @isimo00 and myself, and then we can keep using it sporadically (I'd use it more with Irene and maybe @mcastril to review 4.1.12 dev versions and any issues with testing suite too). That way you wouldn't have to spend too much time on the test if it's too difficult.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:19

Commented on [autosubmit/job/job_list.py line 2727](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-bad488e977334d250f2df049877c45f3L2727)



Hello @kinow , 

I mean, is this one, probably should change the name and move it to another file because it is not only the db anymore: 

https://earth.bsc.es/gitlab/es/autosubmit/-/blob/62d10ca3468d5c4e2d73294cbb6d1158b552a301/test/unit/test_database_regression.py#L192

That test does a run of a job with 3 chunks using the local platform

* Success
* Success with wrappers ( vertical )
* Failure ( the SCRIPT)
* Failure with wrappers ( vertical) ( The script ) 

Each one does basically 

* Autosubmit create t000
* autosubmit run t000

What the test checks:

* The contains of job_data.db
* The Stat files generated
* The logs files recovered with the correct name and no .0. etc
* Perhaps, I should also add the TOTAL_STAT contains

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:27

Commented on [autosubmit/platforms/platform.py line 854](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R854)



If it happens during run time, Autosubmit will crash and complain long before it reaches this ( in the submit_ready_jobs, basically )

This is in line with the recovery fixes. If you do a setstatus and set it to "COMPLETED" it could have the update_logs not set and no id.

I could change the setstatus function.. but then we also need to revise what happens when it is updated through a file or the future GUI. I didn't wanted to use much time there so I applied the prevention there but we can do another fix in another branch

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:34

Commented on [test/unit/test_database_regression.py line 258](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-b8e691c53e499027349985b088df4261L258)



Both codes are equivalent, 

I can leave whatever you prefer.

In the end, I only want to check if there is the expected number of entries.

I was changing the parameters to an absurd amount of retrials or adding more chunks or fewer chunks to do some local tests ( for the copy() stuff), and I found it easier to change the expected_value with the current test.

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:48

Commented on [autosubmit/autosubmit.py line 2199](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-fb87ba4e4225b357016f4298108bcf0dR2199)



Hello @kinow 

That was the idea

I think the main issue is the test's name, as I mentioned somewhere. 

This test db should be renamed to a more general test like test_autosubmit_run()

> But wasn't this change to fix the database test? It looks like the database test was modified here to look for the number of log files, and this merge request is now also fixing/modifying the logic for logs.

This is a regression(or maybe integration?) test.

If the log fails to be retrieved, the entry won't be in the DB. So I need to fix the log recovery to fix the db test.

There was nothing wrong with the DB itself.

But is it True that regression test only include the 

autosubmit create + autosubmit run

There should be another for 

* autosubmit create + autosubmit run + control + c + autosubmit run
* autosubmit create + recovery ...
* etc

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:55

Commented on [autosubmit/autosubmit.py line 2199](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-fb87ba4e4225b357016f4298108bcf0dR2199)



I can leave only the copy() change if you prefer and rename the test, I think it is enough to solve the an autosubmit create + autosubmit run without interruptions.

More than fixing the db test was to fix the failed jobs not working correctly ( that I didn't know it before starting to do the fix)

Edit: Although I don't know if I'll be able to do a regression test/integration in time that checks the behavior of the control +c and set status. ( I did it manually)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:57

Commented everything I believe

Thanks!

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:59

Commented on [autosubmit/job/job_list.py line 2686](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..a50f230b15c2448823b23b1748806c65524bb385#diff-bad488e977334d250f2df049877c45f3R2686)



changed this line in [version 4 of the diff](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37229&start_sha=a50f230b15c2448823b23b1748806c65524bb385#e45075a97470bd3f004d8825e5560953e3c45ee8_2686_2684)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:59

Commented on [autosubmit/autosubmit.py line 2368](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..a50f230b15c2448823b23b1748806c65524bb385#diff-fb87ba4e4225b357016f4298108bcf0dR2368)



changed this line in [version 4 of the diff](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37229&start_sha=a50f230b15c2448823b23b1748806c65524bb385#6bde465286156a9da245a31e64df703a55c76323_2368_2367)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 10:59

added 1 commit

<ul><li>d6a9cad4 - feedback</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37229&start_sha=a50f230b15c2448823b23b1748806c65524bb385)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 11, 2024, 11:13

I'll comment here on my afterthoughts, considering our time limit

> Left some comments about test coverage, and to clarify what's the main goal of the merge request (a single fix or multiple fixes here?).

* First check this 

https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/531#note_328447

* The original idea was to fix the db test on the pipeline. 

* The db test, is a regression test. What failed was the recovery of failed jobs. 

* The db test is, in fact, an `autosubmit create` + '`autosubmit run` test. It is used to check if the DB has the expected entries. For that, it passes through all the run does, as if it were a normal workflow, including the log retrieval. Only when everything is OKAY a job entry is added to the DB.

* The changes, fixes that `autosubmit create + run` test and also adds stuff about the logs being correctly gathered due to the previous point*

* The changes also fix derivates of the `autosubmit create + run` and a regression test doesn't exist for it

------------------------------------------------
Actions to do:

* The db_test should be added to a new file like test_autosubmit_run.py and renamed.


Considering our time limit, what is better

* Move stuff not related exclusively to autosubmit create + run? Then, move each change to it's respective place, considering the new names of the runs

* Stay like this, do some manual tests like I did, and open an issue to separately, include regression tests for variations of the run?

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 08:46

added 1 commit

<ul><li>1e7fe4bd - Changed test name,</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37327&start_sha=d6a9cad411f405bb210b35cd5338618c19114a0d)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 08:50

I've changed the name of the test, and added functions to expand with other run modes.

I'll move the other run types and fixes for them to different branches ( although I'm not sure how to do it)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 08:57

added 1 commit

<ul><li>6ee38c6f - Added few todos</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37329&start_sha=1e7fe4bdb916c2fc0b87df784849735f6e17e35d)

**Comment by kinow** [comment]
In GitLab by @kinow on Dec 12, 2024, 09:03

Commented on [autosubmit/platforms/platform.py line 54](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R54)



Thanks for the explanation Dani! I will see if I can reproduce it until Monday (you are here until next Thu right?).

I think with the `copy` (a shallow copy if I  am not wrong) we will have three copies at one point of `Job`: the one from the process where it was created, then the one we copied when `put`ting, and the other one pickled when `queue.get` is called.

So my only concerns now are if this impacts performance or memory, and if this is not hiding some other issue (as like you, I still do not understand 100% what was causing the failures -- but I understand that the `copy` fixed the test).

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 09:03

added 1 commit

<ul><li>581beffd - disabled the check exit code as it is not working on the pipeline and not important right now</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37331&start_sha=6ee38c6fcfa9f8dc68905f87663c352104ae1e3a)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 09:17

Commented on [autosubmit/platforms/platform.py line 54](https://github.com/BSC-ES/autosubmit/compare/22e0518e169da9ffe33d25ec6852cc6b3ed4a438..9d70142c62520ff4fd78a06e0758665c8eb7bf71#diff-5d19b70fc06bfdd8c8b4686d4aa7fc24R54)



> (as like you, I still do not understand 100% what was causing the failures -- but I understand that the `copy` fixed the test).

That's it

However, I did the renaming of the tests and randomly now the wrapper success is failing only in the pipeline, debugging it

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 09:55

added 1 commit

<ul><li>9d70142c - Adding more chunks to the wrapper success</li></ul>

[Compare with previous version](/gitlab/es/autosubmit/-/merge_requests/531/diffs?diff_id=37334&start_sha=581beffda31e2e2120a195bdea107ec053d6fd85)

**Comment by kinow** [comment]
In GitLab by @dbeltrankyl on Dec 12, 2024, 11:47

mentioned in issue digital-twins/de_340-2/workflow#755

**Comment by dbeltrankyl** [comment]
After adding more info to the tests, I've discovered that the issue with the pipeline is the permissions of the inner_jobs.cmd file. 

For unknown reasons,  in the pipeline the permissions of the cmd only for the vertical wrapper success case is 666 when it should've:

( create_script function)
        os.chmod(os.path.join(self._tmp_path, script_name), 0o755)

At some point this is changed to 666 and the wrappers complains about no permissions to run the job cmd

**Comment by dbeltrankyl** [comment]
> It only evaluates the code lines you changed in this branch, not the covered ones by tests. The purpose is that most of the lines you changed are covered by a test.

Thanks @LuiggiTenorioK 

@kinow 
I've added some regression tests for two cases here #2032 , maybe we can also merge that as it is only two tests without touching AS itself ( did not found blocking issues)

Since the dev module is working well, can we merge this? 

The changes not included in the dev module that you are testing are two chmods for the local platform wrappers

**Pull request merged**
